image: maxking/mailman-ci-runner

variables:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

python3.5:
  script:
    - tox -e py35

python3.6:
  script:
    - tox -e py36

python3.7:
  script:
    - tox -e py37
lint:
  script:
    - tox -e lint

docs:
  script:
    - tox -e docs

upstream:
  script:
    - tox -e dependency
  only:
    variables:
      - $CORE_COMMIT_SHA
